services:
  web:
    image: webdevops/php-apache:8.2
    container_name: tools-kewan-fr
    ports:
      - "8181:80"            # Accès au site sur http://localhost:8082
    volumes:
      - ./web:/app  # Pour live‑reload de votre code en développement
    environment:
      - WEB_DOCUMENT_ROOT=/app
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: devuser
      PMA_PASSWORD: devpass
    ports:
      - "8182:80"
    depends_on:
      - db

volumes:
  db_data: